### ISSUE TITLE
Improved labeling on the Inflation Adustment screen, help text and users guide

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#214] opened 2019-04-11 20:57 UTC
Inflation adjusters should apply to treatments implemented at cycles 2, 3 and 4. And they occur at the beginning, not end, of these cycles.
The note could be clearer.
The help screen could be clearer and with a more complete example.
Good practice would call for modifying the variable names to reflect when the adjustments had been applied, e.g., pval (present value) and pcost (present cost). Also, I want to be sure that I understand the way in which the inflation adjustments (let’s call them that rather than escalators since that would be an inept term for when the adjustments are negative) are being applied in each case so that we know they are being applied consistently  and that their application is consistent with the documentation (written and on/screen clues and help).

Jeremy will work on mocking up these changes and writing new text.

**Comment by lbross** [comment] 2023-06-14 18:27
Closing. This a duplicate of #302.

**Closed by lbross** 2023-06-14 18:27 UTC
