### ISSUE TITLE
FVS: Updating fvs_tree_id during plot input process and fixing references to it in FVS Output Data phase

### ISSUE THREAD

**Issue by sorgtyler** [USFS-PNW/Fia-Biosum-Manager#133] opened 2018-02-22 19:25 UTC
The `fvs_tree_id` field is to be calculated using `Master.Tree.Subp*1000+Master.Tree.Tree`. The field data type is still CHAR(10) for simplicity and compatibility with other tables defined by BioSum. 

During the FVS Input Data creation phase, `Master.Tree.fvs_tree_id` is stored in `FVSIn.FVS_TreeInit.Tree_ID`, but it is stored in a numeric format for compatibility with the FVS table defintions. The FVSOut*.mdb files written to by FVS store the `Tree_ID` using a CHAR(255) data type, however. In the subsequent audit tables and FVSOut*.accdb files created by BioSum, the `fvs_tree_id` field is a CHAR(10) data type.

Currently, this is how I am setting the `fvs_tree_id` in uc_plot_input.cs:
```C#
private void UpdateColumns(...)
{
    ...
    //Update fvs_tree_id column for tracking a tree between BioSum and FVS for lifetime of project
    SetLabelValue(m_frmTherm.lblMsg, "Text", "Updating Tree fvs_tree_id Column...Stand By");
    frmMain.g_oDelegate.ExecuteControlMethod((System.Windows.Forms.Control) this.m_frmTherm, "Refresh");
    m_ado.m_strSQL = "UPDATE " + this.m_strTreeTable + " SET fvs_tree_id = CStr(subp*1000+tree);";
    this.m_ado.SqlNonQuery(this.m_connTempMDBFile, this.m_ado.m_strSQL);
    ...
}
```

In uc_fvs_output.cs, the PRE-append audit passes, but the POST-append audit has some issues. It creates a `tree_fvs_tree_id_work_table` using the `fvs_tree_id` as a primary key, which causes an error now due to repeated `fvs_tree_id` values across stands/`biosum_cond_id`s. Removing this primary key constraint makes the audit pass with warnings due to mismatched FIA and FVS species codes. I think this audit needs to use a compound key of `biosum_cond_id` and `fvs_tree_id` for properly looking up tree records.

**Comment by lbross** [comment] 2018-03-12 21:26
@lpotts: I am updating the Processor code with the fvs_tree_id logic. There are 2 queries that expect the fvs_variant to be part of the fvs_tree_id, which it is no longer. I think I can drop these clauses because we are joining on biosum_cond_id elsewhere in the query. And the cut lists that we are querying from are already segmented by fvs_variant. I don't see any reference to fvs_variant elsewhere in the master.tree table that we could use as an alternative. Please confirm.

query #1: Loads basic information for all the trees
SELECT z.biosum_cond_id, c.biosum_plot_id, z.rxCycle, z.rx, z.rxYear, z.dbh, z.tpa, z.volCfNet, z.drybiot, z.drybiom,
z.FvsCreatedTree_YN, z.fvs_tree_id, z.fvs_species, z.volTsGrs, z.volCfGrs, c.slope, c.elev, c.gis_yard_dist 
FROM fvs_tree_IN_BM_P001_TREE_CUTLIST z, 
(SELECT p.biosum_plot_id,p.gis_yard_dist,p.elev,d.biosum_cond_id,d.slope 
FROM plot p 
INNER JOIN cond d ON p.biosum_plot_id = d.biosum_plot_id) c 
WHERE z.rxpackage='001' AND z.biosum_cond_id = c.biosum_cond_id AND mid(z.fvs_tree_id,1,2)='BM'

query #2: Loads a look-up structure that we use to extract the original spcd for non-FVS created trees
SELECT DISTINCT t.fvs_tree_id, t.biosum_cond_id, t.spcd 
FROM tree t, fvs_tree_IN_BM_P001_TREE_CUTLIST z 
WHERE t.fvs_tree_id = z.fvs_tree_id 
AND t.biosum_cond_id = z.biosum_cond_id AND z.rxpackage='001' 
AND mid(t.fvs_tree_id,1,2)='BM' 
GROUP BY t.fvs_tree_id, t.biosum_cond_id, t.spcd

**Comment by lpotts** [comment] 2018-03-12 21:39
The 2nd query looks ok to remove the FVS_TREE_ID,1,2='BM' expression. The 1st query may need to be looked at a little closer because it is filtering to remove any seedlings or compact trees from the returned dataset.  In the old FVS_TREE_ID,1,2 value, compact trees would have a value of 'CM' and seedlings would have a value of 'ES'.  By including 'BM', one is ensuring the CM and ES trees do not get returned. @lbross

**Comment by lbross** [comment] 2018-03-12 21:46
@lpotts: Thank you! I would never have guessed that that was the intention for querying part of the fvs_tree_id. Is there another indicator of compact trees that we can use in master.tree? I assume we no longer need to worry about seedlings since @sorgtyler is filtering them out earlier in the process.

**Comment by lpotts** [comment] 2018-03-12 21:49
Not in MASTER.TREE since those are FIA trees. COMPACT and SEEDLING trees created by FVS will never be in MASTER.TREE.  The filter is searching against trees in the FVS CUTLIST table.

**Comment by lbross** [comment] 2018-03-12 22:16
Thanks for the clarification. Is there another indicator of compact trees in the FVS CUTLIST? I did some checking with Carlin's CEC project since I ran into Processor errors with seedlings, and this should have filtered them out. In that project, the fvs_tree_id for seedlings was prefixed with the variant rather than 'ES'. Here is an example: 'CAES001456' so my guess is this filter hasn't been working as designed for some time. FVS_TREE_ID,1,2 would always return the variant, even with seedlings. I haven't found any COMPACT trees.

**Comment by lpotts** [comment] 2018-03-12 23:09
I stand corrected based on your example in your previous comment.  So I guess those trees would be processed through the processor.

**Comment by lpotts** [comment] 2018-03-12 23:11
They definitely would drop out of the dataset, however, if you were doing an inner join with the MASTER.TREE table since none of the CM or ES trees are in the MASTER.TREE table.

**Comment by lbross** [comment] 2018-03-13 17:17
I don't think we want to add an inner join with MASTER.TREE because that would cause ALL FVS-created trees to drop out, wouldn't it? Is there another way to screen for the CM trees in the cut list FVS_Tree table? I can't find any examples of CM trees in my test data sets.

**Comment by lbross** [comment] 2018-03-13 17:18
@sorgtyler: Can you post a test dataset where the data has gone through the FVS output process so that I can validate my updated Processor code?

**Comment by sorgtyler** [comment] 2018-03-13 19:06
https://usfs.box.com/s/az3gq72cduqw4bk245482bhn15ndsp5r

- I ran the first 40 stands of the Blue10_demo project (with manually updated the fvs_tree_id) through FVS using the FVSOUT_BM_P001-100-100-100-100.KCP, BM_MortCalc.KCP, and BM_repute.KCP files. 
- I also used the MortCalc and repute KCP files with  FVSOUT_BM_POTFIRE_BaseYr.KCP just in case.
  - *I'm not sure if it was incorrect to use those extra kcp files at all.*
- The last step I executed in BioSum was the post audit, which passed with one spcd warning.

Please let me know if you would prefer a project I made from scratch with a dummy treatment/package.

**Comment by sorgtyler** [comment] 2018-03-13 19:41
That dataset has 265 FVS created trees in it, but they're ES instead of CM.

**Comment by lbross** [comment] 2018-03-13 21:24
This should work for a start. We can discuss testing in greater detail with Jeremy and Carlin. I am looking for trees with the new fvs_tree_id format and it sounds like this should do it.

**Comment by lbross** [comment] 2018-03-14 19:04
I just ran Tyler's test dataset through my updated Processor and it seemed to work. The numbers are close, but differ slightly, when compared to a cut list generated last fall. Always curious, I compared the cut lists and it looks like the difference is mostly in the tpa values. Attaching a sample of trees so others can take a look. You can identify the older version by looking at the fvs_tree_id format.
[new_fvs_tree_id.xlsx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/1812681/new_fvs_tree_id.xlsx)

**Comment by jsfried** [comment] 2018-03-14 19:26
Is there a different process used to derive TPA under the new system? Is it derived from the same source? The new TPA seems to match tpa_unadj out of FIADB-- perhaps this was rounded in the past in order to write to the FVS text input files?

**Comment by sorgtyler** [comment] 2018-03-14 20:14
@jsfried, @lbross I don't round the Master.Tree.tpa_curr field when creating FVSIn.accdb.

**Comment by lbross** [comment] 2018-03-14 20:16
I think this is more a question for @lpotts since it concerns a cut list that was generated last year...

**Comment by lbross** [comment] 2018-03-22 21:36
For FVS-created trees, the fvs_tree_id is NOT calculated. It is generated and copied from FVS. It may begin with either 'ES' for seedlings or 'CM' for compact trees.

**Comment by lbross** [comment] 2019-07-12 18:54
Closing. The current BlueDemo project was created under v5.8.6 and thus has the new FVS_TREE_ID format. It has run all the way through Treatment Optimizer successfully.

**Closed by lbross** 2019-07-12 18:54 UTC
