### ISSUE TITLE
Optimizer throws an SQL Logic Errors on economic filtering 

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#348] opened 2024-09-03 20:45 UTC
We have two scenarios in our CWI project (currently being posted to BioSumBox\projects\cwi) that are throwing an error:
 
![image](https://github.com/user-attachments/assets/a2edce03-6060-4a51-9edd-76b0155a65b6)

when we try to apply an economic filter on net revenue 1 (summed net revenue across the 4 cycles), where we seek to have it >0 or >-200 - in neither case are we able to complete the optimization. This is the input screen that was used:

![image](https://github.com/user-attachments/assets/c79318aa-7a97-438e-9c64-5117d4384b4b)

This is critical for the presentation we are preparing for SAF.

@Cat-Ducat-USDA @lbross

**Comment by lbross** [comment] 2024-09-03 21:05
I discovered this earlier this morning and asked @druepdx to take a look. It is due to the migration of Optimizer parameters to SQLite. There is no workaround.

**Comment by druepdx** [comment] 2024-09-03 21:22
I found the cause of the error and pushed the fix to my fork

**Comment by jsfried** [comment] 2024-09-03 21:28
Does this mean that we might be able to cease and desist on our hail mary MS Access workarounds to geenrate output for these economic filtered scenarios and see a new msi soon?

**Comment by lbross** [comment] 2024-11-13 19:38
Fixed in v5.11.0.

**Closed by lbross** 2024-11-13 19:38 UTC
