### ISSUE TITLE
Tree species issues continue in 580, <sigh>

### ISSUE THREAD

**Issue by jsfried** [USFS-PNW/Fia-Biosum-Manager#151] opened 2018-04-16 04:41 UTC
Spent many hours trying to run processor with the new interim OpCost 10 on CEC this weekend but kept tripping over tree species issues that I cannot explain. We are apparently not yet free of tree species logic glitches, but the "fixes" that finally allowed my project to run are bizarre to me. The 579 originated Slim_CEC project (before being converted to 580, which converted automatically without incident) is in Box under Projects. Please see attached for details. The good news is that these fixes (odd though they are) did allow me to finally process this very large project, apparently with success, and no crashes.
  @carlinstarrs  @lpotts [tree_species_issues.docx](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/1913867/tree_species_issues.docx)

**Comment by carlinstarrs** [comment] 2018-04-16 14:12
This is an open issue in the biosum github 

https://github.com/USFS-PNW/Fia-Biosum-Manager/issues/141

**Comment by lbross** [comment] 2018-04-16 17:13
Will take a look at this later today. Currently looking into the interface between BioSum and OpCost 10. There are some fixes that I made to help Carlin with CEC that aren't incorporated into the posted release of v5.8.0. This includes issue #141.

**Comment by lbross** [comment] 2018-04-16 22:28
@jsfried: Sorry you ran into these issues again. @carlinstarrs and I worked through them a couple of months ago and the fixes, while pending, haven't yet been distributed in an .msi. The problem with spcd 56 is that it is a valid FIA spcd that was not in the FIA_TREE_SPECIES_REF table. We thought we had them all but apparently we did not. It DOES need to be on this table because we need the od_wgt and dry_to_green to run it through Processor.

Our fix was two-fold. The first was to add a check to the tree_species screen that doesn't allow you to add FIA spcd that don't exist in FIA_TREE_SPECIES_REF and tells the analyst why. In the Box project you pointed me to, spcd 56 wasn't yet in the tree_species table and the new code wouldn't let me add it. I agree that the analyst should never have to update the FIA_TREE_SPECIES_REF but we probably should have a business process in place for how to handle this because it may happen again with other spcd. The second part of the fix was to add spcd 56 to the FIA_TREE_SPECIES_REF for future distribution.

Tree species 298: This appears to be working as designed. When I went into the tree species groups screen, there was an entry in the left-hand column with an * next to it for 'other' indicating that it should be added to a tree species group before continuing. Using the screen to assign a tree_species group has the same effect as your manual entry. Carlin added a similar manual entry previously, but she was still on 5..7.9.

**Comment by lbross** [comment] 2018-04-17 20:27
Upon closer examination it appears that the architecture for the tree species groups screen doesn't support tree_species table entries with the same common_name associated with different spcd. When we added spcd 298 to the tree_species table to support FVS-created trees with this spcd, we used the common_name 'other softwood'. This common name was already associated with spcd 299.

I propose 2 steps for this fix:
1. Decide on a unique common_name for spcd 298. In my testing, I used 'other softwood 298'. This creates a unique name entry on the tree_species groups screen that can be assigned to a tree species group.
2. Add an edit to the tree_species screen that prevents an analyst from adding a common_name/spcd combination to the table if the common name is already associated with a different spcd.

Please let me know what the new common_name for spcd 298 should be and I will start work on the fix.

**Comment by lbross** [comment] 2018-04-19 22:58
The new common_names for spcd 298 and 299 will be:
298 - other softwood
299 - unknown dead conifer

**Comment by lbross** [comment] 2018-04-20 17:48
Updated common_name for spcd 299 in tree_species, fvs_tree_species, and fia_tree_species_ref tables. Also added spcd 56 to tree_species table. For analysts who want to update their tables prior to the next release, there is an .accdb in BiosumBox / Temp30Days named  tree_species_issue_151.accdb that contains these updated tables.

**Comment by carlinstarrs** [comment] 2018-06-05 14:31
This issue is still happening for me with CA 56 in 5.8.4. I have made it through all the audits without this species ever coming up, but now when I try to run processor I am getting the CA 56 error. Except this time it's already in the ref_master.tree_species and the scenario_processor_rule_definitions.tree_species_groups_list tables

![image](https://user-images.githubusercontent.com/12533482/40982433-18babb32-6892-11e8-9aa0-9a12ac6b13aa.png)

[biosum_processor_debug.txt](https://github.com/USFS-PNW/Fia-Biosum-Manager/files/2072760/biosum_processor_debug.txt)

![image](https://user-images.githubusercontent.com/12533482/40982537-4e5e2ddc-6892-11e8-8af2-8e862d8aec77.png)

![image](https://user-images.githubusercontent.com/12533482/40982569-62e53f98-6892-11e8-954f-9743abb24837.png)

All the other variants ran through processor happily though

**Comment by carlinstarrs** [comment] 2018-06-05 14:43
I saw in an email that the fvs_tree_species and FIA_SPECIES_REF tables from Lesley's fix  BiosumBox / Temp30Days named tree_species_issue_151.accdb  need to go in an AppData directory and once I replaced those it worked. I guess that means it's missing from that biosum_ref database only

**Comment by lbross** [comment] 2018-06-18 17:59
@carlinstarrs is correct. spcd 56 was missing from FIA_SPECIES_REF. When the tables from issue #156 are implemented, this should no longer be a problem as we added 341 missing species to this table.

**Comment by lbross** [comment] 2019-01-16 23:20
Validated in v5.8.6 using newly generated CEC project.

**Closed by lbross** 2019-01-16 23:20 UTC
